import os
from os.path import join as pjoin

from config import HOME, BASE, CONFIG, ENV_URL,EMBED_WORK

def setup_bash():
    fd = open(pjoin(HOME, '.bashrc'), 'a')
    fd.write('\n')
    fd.write("# Generated by env_init\n")
    fd.write("source ~/%s/bashrc\n" % CONFIG)
    fd.close()

def setup_dircolor():
    os.symlink(pjoin(BASE, "dir_colors"), pjoin(HOME, ".dir_colors"))

def setup_vim():
    os.symlink(pjoin(BASE,'vimrc'), pjoin(HOME,'.vimrc')) 
    os.symlink(pjoin(BASE,'ctags_javascript'), pjoin(HOME,'.ctags'))
    os.mkdir(pjoin(HOME,".vim"))
    os.symlink(pjoin(BASE, "vim_plugin"), pjoin(HOME, ".vim", "plugin"))
    os.symlink(pjoin(BASE, "vim_syntax"), pjoin(HOME, ".vim", "syntax"))

def setup_git():
    os.symlink(pjoin(BASE, 'gitconfig'), pjoin(HOME, '.gitconfig'))

def setup_bin():
    os.symlink(pjoin(BASE, 'bin_script'), pjoin(HOME, 'bin'))

def setup_ssh():
    os.symlink(pjoin(BASE, 'ssh_config'), pjoin(HOME, '.ssh/config'))

def setup_work():
    os.mkdir(pjoin(HOME,EMBED_WORK))

def do():
    setup_dircolor()
    setup_bash()
    setup_vim()
    setup_git()
    setup_bin()
    setup_ssh()
    setup_work()
